spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/schooljournal?createDatabaseIfNotExist=true&useSSL=true&serverTimezone=UTC

    username: root
    password: Dimikal66.
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL55Dialect
    hibernate:
      ddl-auto: update
  # fix for Swagger-ui path matching
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    hiddenmethod:
      filter:
        enabled: true
